blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.show_posts, name='posts'),
]

contact/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.contact, name='contact'),
]

products/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.show_products, name='products'),
    url(r'(?P<slug>[-\w]+)/$', views.product_detail, name='detail'),
]

products_site/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from django.conf import settings

from . import views

urlpatterns = [
    url(r'^$', include('blog.urls', namespace='blog')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^contact/', include('contact.urls', namespace='contact')),
    url(r'^about/', views.about),    
    url(r'^sent/$', views.sent, name='sent'),
]

urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

blog/models.py
from django.db import models

# Create your models here.

class Publisher(models.Model):
    name = models.CharField(max_length=25, unique=True)
    profile_pic = models.ImageField(upload_to='', default='./no_image.png')

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=100, unique=True)
    body = models.TextField()
    posted = models.DateTimeField(db_index=True, auto_now_add=True)
    post_pic = models.ImageField(upload_to='', default='./no_image.png')
    publisher = models.ForeignKey(Publisher)
    link = models.CharField(max_length=100, blank=True)
    linkName = models.CharField(max_length=100, blank=True)


    def __str__(self):
        return self.title

contact/models.py
from django.db import models

# Create your models here.
class WebsiteContact(models.Model):
    subject = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.CharField(max_length=100)
    
    def __str__(self):
        return self.subject

products/models.py
from django.db import models


class Product(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField()
    title = models.CharField(max_length=255)
    description = models.TextField()
    short_description = models.TextField()    
    features = models.TextField()
    size = models.CharField(max_length=25, blank=True)
    color = models.CharField(max_length=25, blank=True)
    price = models.FloatField(default=999.9)
    sale_price = models.FloatField(default=999.9)
    amz_link = models.URLField(max_length=255)
    order = models.IntegerField(default=999)
    image = models.ImageField(upload_to='', default='./no_image.png')
    image2 = models.ImageField(upload_to='', default='./no_image.png')
    image3 = models.ImageField(upload_to='', default='./no_image.png')
    image4 = models.ImageField(upload_to='', default='./no_image.png')
    image5 = models.ImageField(upload_to='', default='./no_image.png')
    image6 = models.ImageField(upload_to='', default='./no_image.png')
    

    def __str__(self):
        return self.title

seo/models.py
from django.db import models

class SEO(models.Model):
    attr = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    content = models.TextField()

    def __str__(self):
        return self.name

contact/forms.py
from django import forms

# our new form
class ContactForm(forms.Form):
    subject = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    message = forms.CharField(required=True,widget=forms.Textarea)

blog/views.py
from django.shortcuts import render

from .models import Post
from products.models import Product


def show_posts(request):   
    posts = Post.objects.order_by('-posted')[0:3]
    product = Product.objects.order_by('order')[0]
    return render(request, 'blog/blog.html', {'posts': posts, 'product': product})

contact/views.py
from django.shortcuts import render, redirect
from django.template.loader import get_template
from django.core.mail import EmailMessage
from django.core.mail import send_mail
from django.template import Context
from .forms import ContactForm
from .models import WebsiteContact


def contact(request):
    form_class = ContactForm

    # new logic!
    if request.method == 'POST':
        form = form_class(data=request.POST)

        if form.is_valid():
            subject = request.POST.get('subject', '')
            email = request.POST.get('email', '')
            message = request.POST.get('message', '')

            # Email the profile with the 
            # contact information
            template = get_template('contact/contact_template.txt')
            context = Context({
                'subject': subject,
                'email': email,
                'message': message,
            })
            content = template.render(context)

            email_message = EmailMessage(
                "New contact form submission from {}".format(email),
                content,
                "manakinproducts.com" +'<support@manakinproducts.com>',
                ['support@manakinproducts.com'],
                headers={'Reply-To': email}
            )
            email_message.send()
            WebsiteContact(subject=subject,email=email,message=message).save()
            return redirect('sent')

    return render(request, 'contact/contact.html', {
        'form': form_class,
    })

products/views.py
from django.shortcuts import render, get_object_or_404

from .models import Product


def show_products(request):
    products = Product.objects.order_by('order')
    return render(request, 'products/products.html', {'products': products})

   
def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug)
    return render(request, 'products/product_detail.html', {'product': product})

products_site/views.py
from django.shortcuts import render

def about(request):
    return render(request, 'about.html')

def sent(request):
    return render(request, 'contact/sent.html')

seo/views.py
from .models import SEO

def get_seos(request):
    context = {}
    context['seos'] = SEO.objects.all()
    return context

blog/templates/blog/blog.html
{% extends "layout.html" %}

{% load humanize %}

{% load static from staticfiles %}

{% block title %}Manakin Products{% endblock %}

{% block css %}
<link href="{% static 'js/ply/ply.css' %}" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block jquery %}
<script src="{% static 'js/ply/Ply.min.js' %}" type="text/javascript" charset="utf-8" defer></script>
{% endblock %}

{% block home %}selected{% endblock %}

{% block wallpaper %}
<div id="wallpaper">
    <h5 style="font-size: 3em">"Quality is not an act, it is a habit"</h5>
    <p>Aristotle</p>
  </div>
{% endblock %}

{% block content %}
<div id="left-column">
  <div class="new-arrival">
    <h4>New Arrival</h4>
    <a href="{% url 'products:detail' slug=product.slug %}" class="new-arrival-link">
      <img class="new-arrival-img" alt="{{ product.title }}" src="{{ product.image.url }}">
      <p class="new-arrival-text">{{ product.title }}</p>
      <button class="new-arrival-button">View Product</button>
    </a>
  </div>
</div>

<div id="blog-container">
  <h6>Manakin News</h6>
  {% for post in posts %}
  <div class="post">
      <div class="post-head">
          <img class="publisher-icon" src="{{ post.publisher.profile_pic.url }}" alt="{{ post.publisher }}">
          <div class="name-date">
            <h2 class="publisher-name">{{ post.publisher }}</h2>
            <h3 class="post-date">{{ post.posted|naturaltime|capfirst }}</h3>
          </div>
      </div>
      <div class="post-body">
          <img class="post-pic img-responsive" src="{{ post.post_pic.url }}"/>
          <h4 class="post-title">{{ post.title }}</h4>
          <p class="post-text">{{ post.body }} <a href="{{post.link}}">{{post.linkName}}</a></p>
      </div>
  </div>
  {% endfor %}

</div>
<div id="right-column">
  <!-- Begin MailChimp Signup Form -->
  <div id="mc_embed_signup">
      <h4>Get Discounts, Gifts and More</h4>
      <p>Sign up to our newsletter to get the latest news, sales and products</p>
      <form action="//manakinproducts.us11.list-manage.com/subscribe/post?u=a1e0fa500772523128ea505f9&amp;id=28d03a4f15" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
          <div id="mc_embed_signup_scroll">
        <!-- <label for="mce-EMAIL">Subscribe to our mailing list</label> -->
        <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="E-Mail" required>
          <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
          <div style="position: absolute; left: -5000px;"><input type="text" name="b_a1e0fa500772523128ea505f9_28d03a4f15" tabindex="-1" value=""></div>
          <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
          </div>
      </form>
  </div>
  <!--End mc_embed_signup-->

  <div id="social-links">
    <h4>Visit Us on Our Social Networks</h4>
    <div id="social-links-img">
      <a class="social-img" href="https://www.twitter.com/ManakinProducts/" target="_blank">
          <img src="{% static 'img/Twitter.ico' %}" alt="Twitter Logo" class="social-icon">
      </a>
      <a class="social-img" href="https://www.facebook.com/ManakinProducts/" target="_blank">
          <img src="{% static 'img/Facebook.ico' %}" alt="Facebook Logo" class="social-icon">
      </a>
      <a class="social-img" href="https://www.pinterest.com/ManakinP/" target="_blank">
          <img src="{% static 'img/Pinterest.ico' %}" alt="Pinterest Logo" class="social-icon">
      </a>
    </div>
  </div>
</div>
{% endblock %}

contact/templates/contact/contact.html
{% extends "layout.html" %}

{% load static from staticfiles %}

{% block title %}Manakin | Contact Us{% endblock %}

{% block contact %}selected{% endblock %}

{% block content %}
<div class="contact-page-container">
    <h1>Contact Us</h1>
    <form class="contact-form" role="form" action="" method="post">
        {% csrf_token %}
        <div class="label-input">
        {{ form.as_p }}
        </div>
        <button type="submit" class="contact-button">Send</button>
    </form>

</div>
{% endblock %}








contact/templates/contact/sent.html
{% extends "layout.html" %}

{% load static from staticfiles %}

{% block title %}Contact Us{% endblock %}

{% block contact %}selected{% endblock %}

{% block content %}
<div class="sent-message-container">
  <h3 class="sent-message">We received your message and will get back to you.</h3>
</div>
{% endblock %}



products/templates/products/product_detail.html
{% extends "layout.html" %}

{% load static from staticfiles %}

{% block title %}Manakin | {{ product.title }} {{ product.sale_price }}${% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
{% endblock %}

{% block jquery %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="{% static 'js/modernizr.js' %}"></script>
<script>
    $(document).ready(function(){
        if (window.matchMedia('(max-width: 40em)').matches) {
          $(".img").addClass("hover");
        }
        if (Modernizr.touch) {
            // show the close overlay button
            $(".close-overlay").removeClass("hidden");
            // handle the adding of hover class when clicked
            $(".img").click(function(e){
                if (!$(this).hasClass("hover")) {
                    $(this).addClass("hover");
                }
            });
            // handle the closing of the overlay
            $(".close-overlay").click(function(e){
                e.preventDefault();
                e.stopPropagation();
                if ($(this).closest(".img").hasClass("hover")) {
                    $(this).closest(".img").removeClass("hover");
                }
            });
        } else {
            // handle the mouseenter functionality
            $(".img").mouseenter(function(){
                $(this).addClass("hover");
                $("#product-page-image").attr("src", $(this).find('img').attr("src"));
            })
            // handle the mouseleave functionality
            .mouseleave(function(){
                $(this).removeClass("hover");
            });
        }
    });
</script>
{% endblock %}

{% block products %}selected{% endblock %}

{% block content %}
<div id="product-detail-page-container">

    <div class="left-col">
      <div class="product-page-desc">
          <h3>{{ product.title }}</h3>
          <p>
            <b>Description:</b> <br>
              {{ product.description }}<br>
          </p>
          <p>
              <b>Features:</b><br>
               {{ product.features }}
          </p>
          <p>
              <b>Size: </b><span class="product-attr">{{ product.size }}</span>
          </p>
          <p>
              <b>Color: </b><span class="product-attr">{{ product.color }}</span>
          </p>
          <p>
              <b>Price: </b><del class="product-attr">{{ product.price }}$</del><b class="product-attr">{{ product.sale_price }}$</b>
          </p>
        
          <a class="buy-button" href="{{ product.amz_link }}" target="_blank">Buy Now</a>
      </div>
    </div>

    <div class="right-col" id="product-page-image-container">
        <img id="product-page-image" src="{{ product.image.url }}" alt="{{ product.title }}">
        <div id="effect-6" class="product-image-list effects clearfix">
            <div class="img image-container">
                <img class="img-list-item" src="{{ product.image.url }}" alt="{{ product.title }}">
                <div class="overlay">
                    <a href="{{ product.image.url }}" class="expand">+</a>
                </div>
            </div>
            <div class="img image-container">
                <img class="img-list-item" src="{{ product.image2.url }}" alt="{{ product.title }}">
                <div class="overlay">
                    <a href="{{ product.image2.url }}" class="expand">+</a>
                </div>
            </div>
            <div class="img image-container">
                <img class="img-list-item" src="{{ product.image3.url }}" alt="{{ product.title }}">
                <div class="overlay">
                    <a href="{{ product.image3.url }}" class="expand">+</a>
                </div>
            </div>
            <div class="img image-container">
                <img class="img-list-item" src="{{ product.image4.url }}" alt="{{ product.title }}">
                <div class="overlay">
                    <a href="{{ product.image4.url }}" class="expand">+</a>
                </div>
            </div>
            <div class="img image-container">
                <img class="img-list-item" src="{{ product.image5.url }}" alt="{{ product.title }}">
                <div class="overlay">
                    <a href="{{ product.image5.url }}" class="expand">+</a>
                </div>
            </div>
            <div class="img image-container">
                <img class="img-list-item" src="{{ product.image6.url }}" alt="{{ product.title }}">
                <div class="overlay">
                    <a href="{{ product.image6.url }}" class="expand">+</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-34160351-1']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<script src="{% static 'js/jquery.magnific-popup.js' %}"></script>
<script src="{% static 'js/gallery.js' %}" type="text/javascript" charset="utf-8"></script>
{% endblock %}








products/templates/products/products.html
{% extends "layout.html" %}

{% load static from staticfiles %}

{% block title %}Manakin | Products{% endblock %}

{% block jquery %}
<script src="http://code.jquery.com/jquery-latest.min.js"></script>
{% endblock %}

{% block products %}selected{% endblock %}

{% block content %}
<div class="products-page-container">
  <h3>Our Products</h3>
  <div class="product-list">
      {% for product in products %}
      <div class="product" id="product-{{ product.pk }}">
        {% if product.title == 'upcoming product' %}
        <figure class="product-figure upcoming">
            <img class="product-image" alt="{{ product.title }}" src="{{ product.image.url }}">
            <figcaption>
                <h3 class="product-title" style="color: #fff; margin-top: 35%; font-size: 1.6em;">Upcoming Product</h3>
            </figcaption>
        </figure>
        {% else %}
        <figure class="product-figure">
            <img class="product-image" alt="{{ product.title }}" src="{{ product.image.url }}">
            <figcaption>
                <h3 class="product-title" style="color: #fff; margin-top: 18%; font-size: 1.6em;">{{ product.title }}</h3>
    
                <p>{{ product.short_description }}</p>
    
                <p><a href="{% url 'products:detail' slug=product.slug %}" class="product-link">View Product</a></p>
            </figcaption>
        </figure>
        {% endif %}
        
      </div>
      {% endfor %}
  </div>
</div>


{% block js %}
<script src="{% static 'js/products.js' %}" type="text/javascript" charset="utf-8"></script>
{% endblock %}

{% endblock %}









templates/about.html
{% extends "layout.html" %}

{% load static from staticfiles %}

{% block title %}Manakin | About Us{% endblock %}

{% block css %}
<link href="{% static 'js/ply/ply.css' %}" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block jquery %}
<script src="{% static 'js/ply/Ply.min.js' %}" type="text/javascript" charset="utf-8" defer></script>
{% endblock %}

{% block about %}selected{% endblock %}

{% block content %}
<div class="about-page-container">

  <div class="about-left-col">
    <h3>About Us</h3>
    <p>Manakin products was founded in 2015 in order to deliver a <a href="{% url 'products:products' %}" id="hqp">High Quality Products</a> to it's costumers.</p>
    <p>We devote ourselves to creating the <br><a href="{% url 'products:products' %}" id="bbe">Best Buying Experience</a> for the smart buyer.</p>
    <p>In Manakin, We work as a team in order to give a <br class="mobile-invisible"><a href="{% url 'contact:contact' %}" id="tcs">Top Customer Service</a> to all of our customers. </p>
  </div>

  <div class="about-right-col">
    <!-- Begin MailChimp Signup Form -->
    <div id="mc_embed_signup">
      <h4>Get Discounts, Gifts and More</h4>
      <p>Sign up to our newsletter to get the latest news, sales and products</p>
      <form action="//manakinproducts.us11.list-manage.com/subscribe/post?u=a1e0fa500772523128ea505f9&amp;id=28d03a4f15" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
          <div id="mc_embed_signup_scroll">
            <!-- <label for="mce-EMAIL">Subscribe to our mailing list</label> -->
            <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="E-Mail" required>
            <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
            <div style="position: absolute; left: -5000px;"><input type="text" name="b_a1e0fa500772523128ea505f9_28d03a4f15" tabindex="-1" value=""></div>
            <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
          </div>
      </form>
    </div>
  <!--End mc_embed_signup-->
  </div>

</div>


<div class="about-icons">
  <div class="row">
    <div class="col-sm-4 text-center">
      <div class="service-box">
        <i class="fa fa-4x fa-star text-primary"></i>
        <h3>High Quality</h3>
      </div>
    </div>
    <div class="col-sm-4 text-center">
      <div class="service-box">
        <i class="fa fa-4x fa-shopping-cart text-primary"></i>
        <h3>Easy Buying</h3>
      </div>
    </div>
    <div class="col-sm-4 text-center">
      <div class="service-box">
        <i class="fa fa-4x fa-group  text-primary"></i>
        <h3>Top Customer Service</h3>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/layout.html
{% load static from staticfiles %}

<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        {% for seo in seos %}
        <meta {{ seo.attr }}="{{ seo.name }}" content="{{ seo.content }}"/> 
        {% endfor %}    
        <title>{% block title %}{% endblock %}</title>
        <link rel="shortcut icon" href="{% static 'img/manakin_logo_title.png' %}" />
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
        <link rel="stylesheet" href="{% static 'css/layout.css' %}">
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
        <link href='https://fonts.googleapis.com/css?family=Slabo+27px' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Arimo:400,700italic&subset=latin,cyrillic-ext' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Lato:700italic' rel='stylesheet' type='text/css'>
        {% block css %}{% endblock %}
        <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.11.3.min.js" defer></script>
        {% block jquery %}{% endblock %}
        <script src="{% static 'js/jquery.sticky-kit.min.js' %}" type="text/javascript" charset="utf-8" defer></script>
        <script src="{% static 'js/app.js' %}" type="text/javascript" charset="utf-8" defer></script>
        <script src="{% static 'js/mobile.js' %}" type="text/javascript" charset="utf-8" defer></script>
    </head>
    <body>
        <header>
          <img src="{% static 'img/menu_button.png' %}" alt="Menu" id="menu-button-mobile">
          <a href="{% url 'blog:posts' %}" id="logo">
            <img src="{% static 'img/manakin_logo.png' %}" alt="Manakin Logo" id="logo-img">
            <img src="{% static 'img/manakin_logo_mobile.png' %}" alt="Manakin Logo" id="logo-img-mobile">
          </a>
          <nav id="top-nav">
            <ul>
              <li><a class="{% block home %}{% endblock %}" href="{% url 'blog:posts' %}">Home</a></li>
              <li><a class="{% block products %}{% endblock %}" href="{% url 'products:products' %}">Products</a></li>
              <li><a class="{% block about %}{% endblock %}" href="{% url 'views.about' %}">About Us</a></li>
              <li><a class="{% block contact %}{% endblock %}" href="{% url 'contact:contact' %}">Contact</a></li>
            </ul>
          </nav>
        </header>
        {% block wallpaper %}{% endblock %}
        <section class="site-container">
            {% block content %}{% endblock %}
        </section>
        <footer>
            <nav id="footer-nav">
                <ul>
                  <li class="footer-li"><a href="{% url 'blog:posts' %}">Home</a></li>
                  <li class="footer-li"><a href="{% url 'products:products' %}">Products</a></li>
                  <li class="footer-li"><a href="{% url 'views.about' %}">About Us</a></li>
                  <li><a href="{% url 'contact:contact' %}">Contact</a></li>
                </ul>
            </nav>
            <a href="https://www.twitter.com/ManakinProducts/" target="_blank">
                <img src="{% static 'img/twitter-wrap.png' %}" alt="Twitter Logo" class="social-icon">
            </a>
            <a href="https://www.facebook.com/ManakinProducts/" target="_blank">
                <img src="{% static 'img/facebook-wrap.png' %}" alt="Facebook Logo" class="social-icon">
            </a>
            <a href="https://www.pinterest.com/ManakinP/" target="_blank">
                <img src="{% static 'img/pinterest-wrap.png' %}" alt="Pinterest Logo" class="social-icon">
            </a>
            <p>&copy; 2015 Manakin Products. All Rights Reserved.</p>
          {% block js %}{% endblock %}
          </footer>
    </body>
</html>

